// <auto-generated />
using System;
using Fundamentos_Entity_Framework_C_.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundamentos_Entity_Framework_C_.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fundamentos_Entity_Framework_C_.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("d638cf70-1148-430a-9c06-04439e6c90c6"),
                            Description = "Actividades sin realizar",
                            Name = "Actividades pendientes",
                            Time = 0
                        },
                        new
                        {
                            CategoryId = new Guid("d638cf70-1148-430a-9c06-04439e6c90c7"),
                            Description = "Actividades de mi interes personal",
                            Name = "Actividades Personales",
                            Time = 5
                        });
                });

            modelBuilder.Entity("Fundamentos_Entity_Framework_C_.Models.Homework", b =>
                {
                    b.Property<Guid>("HomeworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HomeworkId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Homework", (string)null);

                    b.HasData(
                        new
                        {
                            HomeworkId = new Guid("2fd130f6-f752-4e5e-ae63-1c1410a2c920"),
                            CategoryId = new Guid("d638cf70-1148-430a-9c06-04439e6c90c7"),
                            CreatedAt = new DateTime(2025, 3, 7, 0, 46, 27, 834, DateTimeKind.Utc).AddTicks(6852),
                            Description = "Elaborar y revisar el informe de rendimiento del mes",
                            Priority = 0,
                            Title = "Preparar informe mensual",
                            UpdatedAt = new DateTime(2025, 3, 7, 0, 46, 27, 834, DateTimeKind.Utc).AddTicks(6855)
                        },
                        new
                        {
                            HomeworkId = new Guid("2fd130f6-f752-4e5e-ae63-1c1410a2c921"),
                            CategoryId = new Guid("d638cf70-1148-430a-9c06-04439e6c90c6"),
                            CreatedAt = new DateTime(2025, 3, 7, 0, 46, 27, 834, DateTimeKind.Utc).AddTicks(6858),
                            Description = "Seleccionar y leer al menos un capítulo del libro",
                            Priority = 1,
                            Title = "Leer un libro de desarrollo personal",
                            UpdatedAt = new DateTime(2025, 3, 7, 0, 46, 27, 834, DateTimeKind.Utc).AddTicks(6858)
                        });
                });

            modelBuilder.Entity("Fundamentos_Entity_Framework_C_.Models.Homework", b =>
                {
                    b.HasOne("Fundamentos_Entity_Framework_C_.Models.Category", "Category")
                        .WithMany("Homeworks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Fundamentos_Entity_Framework_C_.Models.Category", b =>
                {
                    b.Navigation("Homeworks");
                });
#pragma warning restore 612, 618
        }
    }
}
